### ISSUE TITLE
PDF/MOBI: Content breaks to next page on "Tracking Comparisons" chapter

### ISSUE THREAD

**Issue by dannylonglegs** [pressbooks/pressbooks-book#199]
### Prerequisites

* [x] Can you reproduce the behavior you wish to address with [all plugins except Pressbooks deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/), the latest version of [Pressbooks Book](http://github.com/pressbooks/pressbooks-book/releases/latest/), the latest version of [this book theme](http://github.com/pressbooks/pressbooks-book/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing the issue while using this book theme?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks-book) to see if your bug or enhancement is already listed?

### Description

In "Tracking Comparisons" chapter, the content breaks to next page after the "Tests" header on both 'Before' and 'After' pdf's.

### Steps to Reproduce

1. Navigate to chapter 9 'Tracking Comparisons of Standardized Test Book
2. Scroll to Tests header

**Comment by greatislander** [comment]
See pressbooks/buckram#127.
