### ISSUE TITLE
Clean up about the author sections

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pressbooks-book#854]
**TODO:**
- [x]  Use BEM for contributor classes .contributors, .contributor__name, etc (http://getbem.com/introduction/)
- [x] Make sure we're only targeting classes, never elements with our SCSS in https://github.com/pressbooks/pressbooks-book/blob/dev/packages/buckram/assets/styles/components/specials/_contributors.scss
- [x] Create and use variables instead of hard coding values here: https://github.com/pressbooks/pressbooks-book/blob/dev/packages/buckram/assets/styles/variables/_specials.scss
- [x] Add screenreader helpers for hidden values

Once merged, we will need to complete https://github.com/pressbooks/pressbooks/issues/2371 before releasing.

**Comment by SteelWagstaff** [comment]
WIP at https://github.com/pressbooks/pressbooks-book/tree/pb-book-854-about-author
